### ISSUE TITLE
Shelly-em - LastUpdate stuck at 01-01-1970 00:00

### ISSUE THREAD

**Issue by F43RY** [markus7017/org.openhab.binding.shelly#18]
Hi,
my ShellyEM has lastUpdate value of each meter stuck at "1970-01-01T00:00+01:00" both in basicUI and paperUI. My openhab is 2.5.0 in a raspberry and binding version of "shelly bindings" is 2.5.0 automatically updated from repos.
Can you help me to fix this issue?

Thx

**Comment by markus7017** [comment]
please try this version
https://github.com/markus7017/myfiles/blob/master/org.openhab.binding.shelly-2.5.0-SNAPSHOT.jar

- delete all Shelly things
- you need to deinstall the current version
- open OH console and run “feature:install openhab-transport-coap”
- stop OH
- copy the downloaded jar to OH’s addons folder
- start OH
- re-discover the things

**Comment by markus7017** [comment]
how did you get the localization?

**Comment by F43RY** [comment]
Europe/Rome

**Comment by F43RY** [comment]
Between last 2 steps You wrote, should I "install Add-Ons->Bindings->Shelly Binding"?
Without this step I cannot find any Things.

Thx

**Comment by F43RY** [comment]
I think the .jar You suggested to download is the same I installed from PaperUI. Nothing changed after this update. LastUpdate equals unix timestamp and only some value with unit measurement. :-/

**Comment by markus7017** [comment]
> Between last 2 steps You wrote, should I "install Add-Ons->Bindings->Shelly Binding"?
> Without this step I cannot find any Things.
> 
> Thx
you can't update to the DEV build using PaperUI. As I said you need to deinstall the regular version, install the coap feature and then copy the DEV build to the addons folder

**Comment by markus7017** [comment]
> Europe/Rome
From my understanding that can't provide you the localized channel names - this is the time zone, not the language selection.

 In fact the release version includes only English, the DEV build English and German, maybe the missing units are related to that. Could you please try to switch to English.

**Comment by markus7017** [comment]
> I think the .jar You suggested to download is the same I installed from PaperUI. Nothing changed after this update. LastUpdate equals unix timestamp and only some value with unit measurement. :-/

As mentioned you can't install the DEV build from PaperUI. Please make sure to follow the procedure above incl. deletion and re-discovery of the thing.

In addition please provide the output of the following urls
- http://<device ip>/settings
- http://<device ip>/status
- http://<device ip>/relay/0

**Comment by markus7017** [comment]
just noticed that the EM's meters don't provide a timestamp of the last update
I now simulate that like I do with the sensors
- If some meter values have changed
- use the host's timestamp
This is not 100% accurate, but is better than nothing. 

If you enable CoIoT events the timestamp gets updated with every report from the device.
Nevertheless please provide the output from the above mentioned urls.

A new DEV build has been uploaded to the myfiles repo.

**Comment by F43RY** [comment]
_just noticed that the EM's meters don't provide a timestamp of the last update_
ok, I'was prepearing my answers when I read your last reply. 
Infact the problem is only with EM. With other shellies (shelly 2.5, shelly1pm, shelly plugs and shelly 1) I don't have such issue, "lastUpdate" is shown normally.
Moreover, in EM measurement units are partially filled (only in meter1_watt, meter2_totalEnergy, meter2_voltage) the others are pure numbers with no measurement unit (as shown in a previous post with image). This happens only in EM and in shelly1pm (meter_watt). Rest of shellies I own are correct.

**Comment by F43RY** [comment]
Output of urls you requested:
settings
`{
	"device":{"type":"SHEM","mac":"A4CF12B9F299","hostname":"shellyem-B9F299","num_outputs":1, "num_meters": 0, "num_emeters":2},
	"wifi_ap":{"enabled":false,"ssid":"shellyem-B9F299","key":""},
	"wifi_sta":{"enabled":true,"ssid":"MySSID","ipv4_method":"dhcp","ip":null,"gw":null,"mask":null,"dns":null},
	"wifi_sta1":{"enabled":false,"ssid":null,"ipv4_method":"dhcp","ip":null,"gw":null,"mask":null,"dns":null},
	"mqtt": {"enable":false,"server":"192.168.0.1:123","user":"user","id":"shellyem-B9F299","reconnect_timeout_max":60.000000,"reconnect_timeout_min":2.000000,"clean_session":true,"keep_alive":300,"max_qos":0,"retain":true,"update_period":30},
	"sntp": {"server":"time.google.com"},
	"login":{"enabled":true,"unprotected":false,"username":"username","password":"password"},
	"pin_code":"",
	"name":"",
	"fw":"20191216-090635/v1.5.7@c30657ba",
	"build_info":{"build_id":"20191216-090635/v1.5.7@c30657ba","build_timestamp":"2019-12-16T09:06:35Z","build_version":"1.0"},
	"cloud":{"enabled":false,"connected":false},
	"timezone":"Europe/Rome",
	"lat":45.000000,"lng":11.000000,
	"tzautodetect":true,
	"time":"16:21",
	"hwinfo":{"hw_revision":"prod-2019-06", "batch_id":0},
	"max_power":0,"relays":[
		{
		"name":null,
		"ison":false,
		"has_timer":false,
		"overpower":false,
		"default_state":"off",
		"auto_on":0.00,
		"auto_off":0.00,
		"max_power":0,
		"out_on_url":"http://myOpenhab:8080/shelly/event/shellyem-b9f299/relay/0?type=out_on",
		"out_off_url":"http://myOpenhab:8080/shelly/event/shellyem-b9f299/relay/0?type=out_off",
		"schedule":false,
		"schedule_rules":[]}
	],
	"emeters":[{
		"ctraf_type":50}
	,{
		"ctraf_type":50}
	]
}`

status and status/relay/0 are the same output
`{
	"wifi_sta":{
		"connected":true,"ssid":"MySSID","ip":"192.168.0.210","rssi":-55},
		"cloud":{"enabled":false,"connected":false},
		"mqtt":{"connected":false},
		"time":"16:21",
		"serial":1,
		"has_update":false,
		"mac":"A4CF12B9F299",
		"relays":[{"ison":false,"has_timer":false,"overpower":false,"is_valid":true}],
		"emeters":[
			{"power":0.00,"reactive":0.00,"voltage":236.79,"is_valid":true,"total":351129.2,"total_returned":0.0},
			{"power":175.85,"reactive":-311.32,"voltage":236.79,"is_valid":true,"total":421776.5,"total_returned":0.0}
		],
		"update":{"status":"idle","has_update":false,"new_version":"20191216-090635/v1.5.7@c30657ba","old_version":"20191216-090635/v1.5.7@c30657ba"},
		"ram_total":49960,
		"ram_free":36540,
		"fs_size":233681,
		"fs_free":167668,
		"uptime":80279
}
`

**Comment by F43RY** [comment]
> > Europe/Rome
> > From my understanding that can't provide you the localized channel names - this is the time zone, not the language selection.
> 
> In fact the release version includes only English, the DEV build English and German, maybe the missing units are related to that. Could you please try to switch to English.

Sorry but my first time install an addons manually. I forgot to add "shelly" to bindings within services/addons.cfg file. Now I upgraded to your snapshot

**Comment by markus7017** [comment]
> Infact the problem is only with EM. With other shellies (shelly 2.5, shelly1pm, shelly plugs and shelly 1) I don't have such issue, "lastUpdate" is shown normally.

Yes, the EM has a different type of Meter, which is lacking the timestamp information. I think the solution I implemented a work around, but full fills it's function.

> "emeters":[ {"power":0.00,"reactive":0.00,"voltage":236.79,"is_valid":true,"total":351129.2,"total_returned":0.0}, {"power":175.85,"reactive":-311.32,"voltage":236.79,"is_valid":true,"total":421776.5,"total_returned":0.0} ],

The JSON is the proof that the emeters include a timestamp. So we stay with the work around.

> Moreover, in EM measurement units are partially filled (only in meter1_watt, meter2_totalEnergy, meter2_voltage) the others are pure numbers with no measurement unit (as shown in a previous post with image). 
I check the channel definition, which looks good, e.g. reactiveWatts uses the same display pattern than currentWatts and the binding sets the correct quantity type, which should then result in displaying the value and the unity.

> This happens only in EM and in shelly1pm (meter_watt). Rest of shellies I own are correct.

This is even more strange, because the 1PM uses exactly the same meter definition like the Shelly 2 and 2.5. Could yo please try to switch to English, maybe that gives an indication.

The other thing you could do is to create a TRACE log
- open OH console
- enter "log:set TRACE org.openhab.binding.shelly"
- wait a while until you see the meter updates in the log
- and provide this sequence
this shows the channel update as well as the unity type the binding sets on a channel update.

**Comment by F43RY** [comment]
Maybe update to your snapshot was not fine, sorry but I'm unexperienced.

Is the following code enough?


`18:22:45.787 [TRACE] [ly.internal.handler.ShellyBaseHandler] - shellyem-b9f299: Updating status
18:22:45.790 [TRACE] [ing.shelly.internal.api.ShellyHttpApi] - HTTP GET for : http://192.168.0.210/status
18:22:45.876 [TRACE] [ing.shelly.internal.api.ShellyHttpApi] - HTTP response from : {"wifi_sta":{"connected":true,"ssid":"MySSID","ip":"192.168.0.210","rssi":-54},"cloud":{"enabled":false,"connected":false},"mqtt":{"connected":false},"time":"18:22","serial":1,"has_update":false,"mac":"A4CF12B9F299","relays":[{"ison":false,"has_timer":false,"overpower":false,"is_valid":true}],"emeters":[{"power":0.00,"reactive":0.00,"voltage":234.29,"is_valid":true,"total":351161.4,"total_returned":0.0},{"power":240.01,"reactive":-256.01,"voltage":234.29,"is_valid":true,"total":422143.3,"total_returned":0.0}],"update":{"status":"idle","has_update":false,"new_version":"20191216-090635/v1.5.7@c30657ba","old_version":"20191216-090635/v1.5.7@c30657ba"},"ram_total":49960,"ram_free":36792,"fs_size":233681,"fs_free":167668,"uptime":86960}
18:22:45.882 [TRACE] [y.internal.handler.ShellyRelayHandler] - shellyem-b9f299: Updating 1 relay(s)
18:22:45.886 [TRACE] [ing.shelly.internal.api.ShellyHttpApi] - HTTP GET for : http://192.168.0.210/status/relay/0
18:22:45.972 [TRACE] [ing.shelly.internal.api.ShellyHttpApi] - HTTP response from : {"wifi_sta":{"connected":true,"ssid":"MySSID","ip":"192.168.0.210","rssi":-54},"cloud":{"enabled":false,"connected":false},"mqtt":{"connected":false},"time":"18:22","serial":1,"has_update":false,"mac":"A4CF12B9F299","relays":[{"ison":false,"has_timer":false,"overpower":false,"is_valid":true}],"emeters":[{"power":0.00,"reactive":0.00,"voltage":234.29,"is_valid":true,"total":351161.4,"total_returned":0.0},{"power":240.01,"reactive":-256.01,"voltage":234.29,"is_valid":true,"total":422143.3,"total_returned":0.0}],"update":{"status":"idle","has_update":false,"new_version":"20191216-090635/v1.5.7@c30657ba","old_version":"20191216-090635/v1.5.7@c30657ba"},"ram_total":49960,"ram_free":36784,"fs_size":233681,"fs_free":167668,"uptime":86961}
18:22:45.977 [TRACE] [ly.internal.handler.ShellyBaseHandler] - shellyem-b9f299: Updating 2 e-meter(s)
18:22:45.991 [TRACE] [ly.internal.handler.ShellyBaseHandler] - shellyem-b9f299: Channel meter1#voltage updated with 234.29 V (type class org.eclipse.smarthome.core.library.types.QuantityType).
18:22:45.999 [INFO ] [smarthome.event.ItemStateChangedEvent] - ShellyemB9f299192168048_Meter1_Voltage changed from 235.35 to 234.29
18:22:46.066 [TRACE] [ly.internal.handler.ShellyBaseHandler] - shellyem-b9f299: Channel meter2#currentWatts updated with 240.010 W (type class org.eclipse.smarthome.core.library.types.QuantityType).
18:22:46.067 [INFO ] [home.event.GroupItemStateChangedEvent] - gVoltage changed from 236.23 to 235.88 through ShellyemB9f299192168048_Meter1_Voltage
18:22:46.080 [TRACE] [ly.internal.handler.ShellyBaseHandler] - shellyem-b9f299: Channel meter2#reactiveWatts updated with -256.010 W (type class org.eclipse.smarthome.core.library.types.QuantityType).
18:22:46.093 [TRACE] [ly.internal.handler.ShellyBaseHandler] - shellyem-b9f299: Channel meter2#voltage updated with 234.29 V (type class org.eclipse.smarthome.core.library.types.QuantityType).
18:22:46.094 [INFO ] [home.event.GroupItemStateChangedEvent] - gPower changed from 238.450 to 240.010 through ShellyemB9f299192168048_Meter2_Watt
18:22:46.103 [TRACE] [ly.internal.handler.ShellyBaseHandler] - shellyem-b9f299: Channel device#uptime updated with 86960 s (type class org.eclipse.smarthome.core.library.types.QuantityType).
18:22:46.110 [INFO ] [smarthome.event.ItemStateChangedEvent] - ShellyemB9f299192168048_Meter2_Watt changed from 238.450 W to 240.010 W
18:22:46.122 [INFO ] [smarthome.event.ItemStateChangedEvent] - ShellyemB9f299192168048_Meter2_ReactiveWatt changed from -249.900 W to -256.010 W
18:22:46.130 [INFO ] [smarthome.event.ItemStateChangedEvent] - ShellyemB9f299192168048_Meter2_Voltage changed from 235.35 V to 234.29 V
18:22:46.136 [INFO ] [home.event.GroupItemStateChangedEvent] - gVoltage changed from 235.88 to 235.53 through ShellyemB9f299192168048_Meter2_Voltage
`

**Comment by F43RY** [comment]
> Could yo please try to switch to English, maybe that gives an indication.
Do you mean from PaperUI->Preferences-UserInterface or translate each label Item of my EM?

**Comment by markus7017** [comment]
> Maybe update to your snapshot was not fine, sorry but I'm unexperienced.

Did you followed this procedure?
- download DEV build from https://github.com/markus7017/myfiles/blob/master/org.openhab.binding.shelly-2.5.0-SNAPSHOT.jar?raw=true
- delete all Shelly things
- deinstall the current version in PaperUI:Addons:Bindings:Shelly:Uninstall
- stop OH
- run "openhab-cli clean-cache"
- start OH, wait until initialized
- open OH console and run “feature:install openhab-transport-coap”
- copy the downloaded jar to OH’s addons folder, wait until initialized (or restart OH)
- re-discover the things

> Is the following code enough?

I see
Updating 2 e-meter(s)
Channel meter1#voltage updated with 234.29 **V** - fine
Channel meter2#currentWatts updated with 240.010 **W** - fine
Channel meter2#reactiveWatts updated with -256.010 **W** - fine
Channel meter2#voltage updated with 234.29 **V** - ok
Channel device#uptime updated with **86960 s** - ok
Those are not all values (because the others have not changed), but it shows that all of those updates include the quantity type, so I don't understand why PaperUI doesn't display them.

> Do you mean from PaperUI->Preferences-UserInterface or translate each label Item of my EM?

Yes. Did you translated the labels?

If you like you could contribute the Spanish translations once we fixed the issue. This would require a resource file like this one: https://github.com/markus7017/openhab2-addons/blob/shelly-25final-2/bundles/org.openhab.binding.shelly/src/main/resources/ESH-INF/i18n/shelly_de.properties, but let's focus on the current issue.

**Comment by F43RY** [comment]
> Did you followed this procedure?
> 
>     * download DEV build from https://github.com/markus7017/myfiles/blob/master/org.openhab.binding.shelly-2.5.0-SNAPSHOT.jar?raw=true
> 
>     * delete all Shelly things
OK, deleted from PaperUI
> 
>     * deinstall the current version in PaperUI:Addons:Bindings:Shelly:Uninstall
OK, deleted from PaperUI
> 
>     * stop OH
OK, sudo service openhab2 stop
> 
>     * run "openhab-cli clean-cache"
OK, done
> 
>     * start OH, wait until initialized
sudo service openhab2 start
> 
>     * open OH console and run “feature:install openhab-transport-coap”
`openhab-runtime-compat1x                          │ 2.5.0            │          │ Started     │ distro-2.5.0                │ Compatibility layer for openHAB 1 add-ons
openhab-transport-coap                            │ 2.5.0            │ x        │ Started     │ distro-2.5.0                │ CoAP Transport
openhab-transport-http                            │ 2.5.0            │          │ Started     │ distro-2.5.0                │ HTTP Transport
`
> 
>     * copy the downloaded jar to OH’s addons folder, wait until initialized (or restart OH)
`usr/share/openhab2/addons $ ll
totale 160
-rw-r--r-- 1 openhab openhab 156593 dic 30 21:25 org.openhab.binding.shelly-2.5.0-SNAPSHOT.jar
-rw-r--r-- 1 openhab openhab     70 dic 15 23:56 README
`
> 
>     * re-discover the things
things appeared after a while, not immediately. Now, I'm sure I'm using your jar. System shelly binding is uninstalled and I dicovered my shellys
> 
>

**Comment by F43RY** [comment]
After clean-cache and using your jar datetime are correctly shown but meas Units not yet. Here following the new screenshot with original label and translations.
![shellyem](https://user-images.githubusercontent.com/4217502/71600054-ae999b80-2b4d-11ea-9f14-4d7e1e166ab5.png)

**Comment by markus7017** [comment]
where do the translations come from?

**Comment by F43RY** [comment]
I translated (Italian, not spanish)

**Comment by F43RY** [comment]
Take a look at the following event within the attached log

`21:50:54.870 [INFO ] [smarthome.event.ItemStateChangedEvent] - ShellyemB9f299192168048_Meter1_Voltage changed from 233.03 to 234.35`

[log_em.txt](https://github.com/markus7017/org.openhab.binding.shelly/files/4011001/log_em.txt)

**Comment by F43RY** [comment]
> If you like you could contribute the Spanish translations once we fixed the issue. This would require a resource file like this one: https://github.com/markus7017/openhab2-addons/blob/shelly-25final-2/bundles/org.openhab.binding.shelly/src/main/resources/ESH-INF/i18n/shelly_de.properties, but let's focus on the current issue.

I'm trying to translate into _shelly_it.properties_ but for me is hard from dutch. "Ich sprache nicht deutsch".
Do you have a _shelly_en.properties_ file? It would be easyer for me.

**Comment by F43RY** [comment]
> After clean-cache and using your jar datetime are correctly shown but meas Units not yet. Here following the new screenshot with original label and translations.
> ![shellyem](https://user-images.githubusercontent.com/4217502/71600054-ae999b80-2b4d-11ea-9f14-4d7e1e166ab5.png)

Unfortunately now Signal Strength doesn't work any more.

**Comment by markus7017** [comment]
Did you deleted the things and re-discovrred? It looks like you have the latest jar, but an old thing definition.

**Comment by F43RY** [comment]
yes, I did.

**Comment by markus7017** [comment]
> yes, I did.

Did you linked all channels?

Do you have channels like device#timeoutErrors and device#timeoutsRecovered?

If not the thing definition doesn’t match the jar
- delete the things
- stop OH
- clean JSON DB (delete all Shelly entries)
- start OH
- re-discover things
- link channels to items

This would also explain why WiFi signal is not working anymore: because the channel was renamed

**Comment by F43RY** [comment]
No, i don't linked all channels and Yes, I can see timeouts channels but didn't link them .
Anyway. I'm going to delete things and this time I'm deleting items too. stop OH, clean-cache, delete tmp and cache folders, restart OH and rediscover again and link new items.

**Comment by markus7017** [comment]
strange, make sure to cleanout all JSONDB filed, sometimes there are left overs

**Comment by F43RY** [comment]
I'll update You as soon as I finished above steps

**Comment by F43RY** [comment]
Now several Exceptions at start.........

`2019-12-31 15:21:26.765 [WARN ] [org.apache.felix.fileinstall        ] - Error while starting bundle: file:/usr/share/openhab2/addons/org.openhab.binding.shelly-2.5.0-SNAPSHOT.jar
org.osgi.framework.BundleException: Could not resolve module: org.openhab.binding.shelly [97]
  Unresolved requirement: Import-Package: org.eclipse.californium.core; version="[2.0.0,3.0.0)"

	at org.eclipse.osgi.container.Module.start(Module.java:444) ~[org.eclipse.osgi-3.12.100.jar:?]
	at org.eclipse.osgi.internal.framework.EquinoxBundle.start(EquinoxBundle.java:383) ~[org.eclipse.osgi-3.12.100.jar:?]
	at org.apache.felix.fileinstall.internal.DirectoryWatcher.startBundle(DirectoryWatcher.java:1260) [bundleFile:3.6.4]
	at org.apache.felix.fileinstall.internal.DirectoryWatcher.startBundles(DirectoryWatcher.java:1233) [bundleFile:3.6.4]
	at org.apache.felix.fileinstall.internal.DirectoryWatcher.startAllBundles(DirectoryWatcher.java:1221) [bundleFile:3.6.4]
	at org.apache.felix.fileinstall.internal.DirectoryWatcher.doProcess(DirectoryWatcher.java:515) [bundleFile:3.6.4]
	at org.apache.felix.fileinstall.internal.DirectoryWatcher.process(DirectoryWatcher.java:365) [bundleFile:3.6.4]
	at org.apache.felix.fileinstall.internal.DirectoryWatcher.run(DirectoryWatcher.java:316) [bundleFile:3.6.4]
2019-12-31 15:21:36.818 [WARN ] [org.apache.felix.fileinstall        ] - Error while starting bundle: file:/usr/share/openhab2/addons/org.openhab.binding.shelly-2.5.0-SNAPSHOT.jar
org.osgi.framework.BundleException: Could not resolve module: org.openhab.binding.shelly [97]
  Unresolved requirement: Import-Package: org.eclipse.californium.core; version="[2.0.0,3.0.0)"

	at org.eclipse.osgi.container.Module.start(Module.java:444) ~[org.eclipse.osgi-3.12.100.jar:?]
	at org.eclipse.osgi.internal.framework.EquinoxBundle.start(EquinoxBundle.java:383) ~[org.eclipse.osgi-3.12.100.jar:?]
	at org.apache.felix.fileinstall.internal.DirectoryWatcher.startBundle(DirectoryWatcher.java:1260) [bundleFile:3.6.4]
	at org.apache.felix.fileinstall.internal.DirectoryWatcher.startBundles(DirectoryWatcher.java:1233) [bundleFile:3.6.4]
	at org.apache.felix.fileinstall.internal.DirectoryWatcher.startAllBundles(DirectoryWatcher.java:1221) [bundleFile:3.6.4]
	at org.apache.felix.fileinstall.internal.DirectoryWatcher.doProcess(DirectoryWatcher.java:515) [bundleFile:3.6.4]
	at org.apache.felix.fileinstall.internal.DirectoryWatcher.process(DirectoryWatcher.java:365) [bundleFile:3.6.4]
	at org.apache.felix.fileinstall.internal.DirectoryWatcher.run(DirectoryWatcher.java:316) [bundleFile:3.6.4]
`

**Comment by F43RY** [comment]
I'm giving up...
After deleting everything (items too). System discovered shellies as below:
`2019-12-31 15:34:20.844 [INFO ] [g.discovery.internal.PersistentInbox] - Added new thing 'shelly:shelly25-relay:691f93' to inbox.
2019-12-31 15:34:20.850 [INFO ] [g.discovery.internal.PersistentInbox] - Added new thing 'shelly:shellyem:b9f299' to inbox.
2019-12-31 15:34:20.857 [INFO ] [g.discovery.internal.PersistentInbox] - Added new thing 'shelly:shelly1:93ac3e' to inbox.
2019-12-31 15:34:20.862 [INFO ] [g.discovery.internal.PersistentInbox] - Added new thing 'shelly:shellyplugs:3cf05f' to inbox.
2019-12-31 15:34:20.869 [INFO ] [g.discovery.internal.PersistentInbox] - Added new thing 'shelly:shelly1pm:b1d10f' to inbox.
2019-12-31 15:34:20.876 [INFO ] [g.discovery.internal.PersistentInbox] - Added new thing 'shelly:shelly25-roller:5db2f6' to inbox.
`
but timeouts fields are not shown any more.  :-(

- Signal strength Ok
- lastUpdate Ok
In red values with no unit measurements

![shellyem](https://user-images.githubusercontent.com/4217502/71625234-fddfda80-2be6-11ea-9e93-a3150daa0b7a.png)

**Comment by markus7017** [comment]
please provide a bundle:list output

the timeoutErrors and timeoutsRecovered channels are shown when you click on [More] in the channel configuration

**Comment by markus7017** [comment]
> Take a look at the following event within the attached log
> `21:50:54.870 [INFO ] [smarthome.event.ItemStateChangedEvent] - ShellyemB9f299192168048_Meter1_Voltage changed from 233.03 to 234.35`

This is the binding action
shellyem-b9f299: Channel meter1#voltage updated with 234.35 V (type class org.eclipse.smarthome.core.library.types.QuantityType).
this what the framework does on item change
ShellyemB9f299192168048_Meter1_Voltage changed from 233.03 to 234.35

Did you defined the items in a text file? Please send the definitions.
or linked in PaperUI?

**Comment by F43RY** [comment]
> please provide a bundle:list output

[bundle_list.txt](https://github.com/markus7017/org.openhab.binding.shelly/files/4013118/bundle_list.txt)

> 
> the timeoutErrors and timeoutsRecovered channels are shown when you click on [More] in the channel configuration

Ok, found them and uptime, autoon/off ecc. Linked timeouts and in control their value is "-NaN"

**Comment by markus7017** [comment]
> [bundle_list.txt]

bundle_list.txt seems to be an extract of a log, not the bundle:list output

> Ok, found them and uptime, autoon/off ecc. Linked timeouts and in control their value is "-NaN"

wait a minute or so, they'll come.

> linked in PaperUI

that's really creepy. I checked XML definitions, code and also code of another binding. Looks good, but...

I ordered a EM, but it will arrive mid January, maybe we'll figure out the problem without it (I think it's a tiny detail to find)

**Comment by F43RY** [comment]
> bundle_list.txt seems to be an extract of a log, not the bundle:list output

Sorry, attached wrong file. Re-download it again. Updated link.

**Comment by markus7017** [comment]
It gets even more strange
Voltage of the first meter does not have the V, but the one of the 2nd meter
meter1 and meter2 use exactly the same channel definitions

**Comment by markus7017** [comment]
I posted a comment in the community to find someone with an EM and willing to support
https://community.openhab.org/t/shelly-binding/56862/768?u=markus7017
